apiVersion: v1
kind: Service
metadata:
  name: graphrag-ui
  namespace: g-shama-graphrag-dev
  labels:
    app: graphrag-ui
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: reflex-frontend
      port: 3000
      targetPort: reflex-frontend
    - name: reflex-backend
      port: 8000
      targetPort: reflex-backend
  selector:
    app: graphrag-ui
