apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: graphrag-ui
    app.kubernetes.io/component: graphrag-ui
    app.kubernetes.io/instance: graphrag-ui
    app.kubernetes.io/name: graphrag-ui
  name: graphrag-ui
  namespace: g-shama-graphrag-dev
spec:
  lookupPolicy:
    local: false
