apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphrag-pvc
  namespace: g-shama-graphrag-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vastdata-cloud
  volumeMode: Filesystem
