apiVersion: v1
kind: Secret
metadata:
  name: github-graphrag-webapp
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBOTNSK1VseDFGV2hDaVAyekFwRDhKU2VqV0tZWTB0T0JnUEZacEs3QXYzQUFBQUpqcXVmeGM2cm44ClhBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQTkzUitVbHgxRldoQ2lQMnpBcEQ4SlNlaldLWVkwdE9CZ1BGWnBLN0F2M0EKQUFBRUJSWE9MYnNFOFRXeUtjT1NWT3BOUGpHWG1TODdEZmZnbmpzdGxxTnE4dUJqM2RINVNYSFVWYUVLSS9iTUNrUHdsSgo2TllwaGpTMDRHQThWbWtyc0MvY0FBQUFEM056TVRrNU9EQkFibmwxTG1Wa2RRRUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
